# Site settings
title: ljun51
subtitle: 个人网站
email: ljun51@outlook.com
description: ljun51（牛古）的个人网站，分享IT技术、生活点滴。包括Java、Golang、Javascript等前端、后端的技术，还有各种开发工具、开发平台的技术。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ljun51.github.io" # the base hostname & protocol for your site
author:
#street_address: 1234 Somewhere Road
street_address: Furong Road
city: Changsha 
state: China 
zip_code: 410000
country: 
phone: (+86) 1867031****

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/ljun51
gitlab_url: 
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: 
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
